config/routes.rb
Rails.application.routes.draw do
  resources :welcome
  root 'welcome#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@test = params[:test]
  end
  def show
  	@id = params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Params</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Params Hash</h1>

<p>The params hash is a collection of data that comes through your application in a request. So this data can come through various places. You can submit a form, and that sends over some data. Your URL might contain a chunk of data. The end of your URL might contain some GET request parameters.</p>

<p>rails just knows to collect these things and put them in your application for you to work with.</p>

<h3>GET Request Parameters</h3>
<h4>Welcome Controller</h4>
<p>def index
  	<br>@test = params[:test]
<br>end</p>
<p>type in <strong>?test=hello </strong>after the URL and press enter</p>
<p>Parameters: {"test"=>"<strong><%= @test %></strong>"}</p>
<p>What's happening?</p>
<p>The URL contains some GET request parameters that rails intelligently picks up. The Welcome Controller has an instance variable @test which is used to print out in the Index View what you typed in the URL.</p>

<h3><%= link_to 'ID Parameters', welcome_path('replaceme') %></h3>

<h3>POST Request Parameters</h3>

app/views/welcome/show.html.erb
<h1>here's the ID as a params</h1>
<h4>Welcome Controller</h4>
<p>def show
  	<br>@id = params[:id]
<br>end</p>
<p>replace the 'replaceme' text in the URL and press enter</p>
<p>Parameters: {"id"=>"<strong><%= @id %></strong>"}</p>
<h4>applications of the ID as a params</h4>